"""Known-answer tests for the ML-KEM (Kyber) core.

The guiding discipline: self-consistency proves nothing. A wrong-but-consistent
implementation passes its own round-trip. So the strongest test here is the
cross-implementation KAT, whose expected digests were generated by the C
reference kyber_fips203_hardened.c and are pinned below. The Python core must
reproduce them byte-for-byte.
"""
import hashlib
import random
import unittest

from crypto.kyber.params import N, Q, MLKEM512, MLKEM768, MLKEM1024
from crypto.kyber import primitives as prim
from crypto.kyber.mlkem import mlkem_keygen, mlkem_encaps, mlkem_decaps
from crypto.kyber import keygen, encaps, decaps

PARAM_SETS = (MLKEM512, MLKEM768, MLKEM1024)

# Reference sizes from FIPS 203 (README section 2.1): (ek, dk, ct, ss).
REF_SIZES = {
    "ML-KEM-512":  (800, 1632, 768, 32),
    "ML-KEM-768":  (1184, 2400, 1088, 32),
    "ML-KEM-1024": (1568, 3168, 1568, 32),
}

# Fixed seeds matching the C reference's deterministic regression KAT, and the
# expected SHA3-256(ek || ct || K) digest each produces. Any change to the
# arithmetic, sampling, or byte packing changes these digests.
KAT_D = bytes([0x7f, 0x9c, 0x2b, 0xa4, 0xe8, 0x8f, 0x82, 0x7d, 0x61, 0x60, 0x45, 0x07, 0xa7, 0x33, 0x87, 0x12,
               0x10, 0x50, 0x40, 0x05, 0x6f, 0xe8, 0x3b, 0x57, 0x11, 0x89, 0x20, 0xc2, 0x65, 0x23, 0x41, 0x00])
KAT_Z = bytes((0xA0 + i) & 0xFF for i in range(32))
KAT_M = bytes((0x10 + i) & 0xFF for i in range(32))
KAT_DIGEST = {
    "ML-KEM-512":  "2c41c411e99dff38d6db887ffc7878643fb4871a7622ac2b7651386e76335efd",
    "ML-KEM-768":  "b7141a49c3be466f7c7dee059e00d086153537eaefad0ce1a7785b3504984afa",
    "ML-KEM-1024": "1519f91ffb2d7f4cad3556cdea9e7361dcdd91046ffbaf79d4eb3f13c530c9ab",
}


class TestHashKATs(unittest.TestCase):
    """Empty-string vectors validate the hash roles and domain separation."""

    def test_empty_string_digests(self):
        self.assertEqual(prim.H(b"").hex(),
            "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a")
        self.assertEqual(prim.G(b"").hex(),
            "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a6"
            "15b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26")
        self.assertEqual(prim.J(b"").hex(),
            "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f")
        # SHAKE128 squeezed to 32 bytes, the XOF that expands matrix A.
        self.assertEqual(hashlib.shake_128(b"").digest(32).hex(),
            "7f9c2ba4e88f827d616045507605853ed73b8093f6efbc88eb1a6eacfa66ef26")


class TestNTT(unittest.TestCase):
    def test_ntt_intt_identity(self):
        rng = random.Random(1)
        for _ in range(50):
            original = [rng.randrange(Q) for _ in range(N)]
            work = list(original)
            prim.poly_ntt(work)
            prim.poly_intt(work)
            self.assertEqual(work, original)

    def test_basemul_vs_schoolbook(self):
        rng = random.Random(2)
        for _ in range(50):
            a = [rng.randrange(Q) for _ in range(N)]
            b = [rng.randrange(Q) for _ in range(N)]
            ah, bh = list(a), list(b)
            prim.poly_ntt(ah)
            prim.poly_ntt(bh)
            ch = prim.poly_basemul(ah, bh)
            prim.poly_intt(ch)
            self.assertEqual(ch, _schoolbook(a, b))


def _schoolbook(a, b):
    """Negacyclic multiply in R_q = Z_q[X]/(X^256+1). The wrap X^256 = -1 is the
    minus sign. This is the slow reference the fast NTT path is checked against."""
    acc = [0] * (2 * N)
    for i in range(N):
        for j in range(N):
            acc[i + j] += a[i] * b[j]
    r = [0] * N
    for i in range(N):
        r[i] = (acc[i] - acc[i + N]) % Q
    return r


class TestSizes(unittest.TestCase):
    def test_serialized_sizes(self):
        for p in PARAM_SETS:
            ek, dk = mlkem_keygen(p, KAT_D, KAT_Z)
            ss, ct = mlkem_encaps(p, ek, KAT_M)
            self.assertEqual(
                (len(ek), len(dk), len(ct), len(ss)), REF_SIZES[p.name], p.name)


class TestKEMRoundTrip(unittest.TestCase):
    def test_roundtrip_fresh_randomness(self):
        for p in PARAM_SETS:
            for _ in range(100):
                ek, dk = keygen(p.name)
                ss_sender, ct = encaps(p.name, ek)
                ss_receiver = decaps(p.name, dk, ct)
                self.assertEqual(ss_sender, ss_receiver, p.name)

    def test_implicit_rejection(self):
        # Flipping a ciphertext byte must yield a different secret, not an error.
        for p in PARAM_SETS:
            ek, dk = keygen(p.name)
            ss_sender, ct = encaps(p.name, ek)
            tampered = bytearray(ct)
            tampered[0] ^= 0xFF
            ss_reject = decaps(p.name, dk, bytes(tampered))
            self.assertNotEqual(ss_reject, ss_sender, p.name)
            self.assertEqual(len(ss_reject), 32)


class TestCrossImplementationKAT(unittest.TestCase):
    """The strongest check: match the C reference byte-for-byte on fixed seeds."""

    def test_pinned_digests(self):
        for p in PARAM_SETS:
            ek, dk = mlkem_keygen(p, KAT_D, KAT_Z)
            ss, ct = mlkem_encaps(p, ek, KAT_M)
            digest = hashlib.sha3_256(ek + ct + ss).hexdigest()
            self.assertEqual(digest, KAT_DIGEST[p.name], p.name)
            # The pinned secret also decapsulates correctly.
            self.assertEqual(decaps(p.name, dk, ct), ss, p.name)


if __name__ == "__main__":
    unittest.main()
